Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content
    - ${MOOSE_DIR}/modules/scalar_transport/doc/content
    - ${MOOSE_DIR}/modules/chemical_reactions/doc/content
    - ${MOOSE_DIR}/modules/navier_stokes/doc/content
    - ${MOOSE_DIR}/modules/thermal_hydraulics/doc/content
    - ${MOOSE_DIR}/modules/fluid_properties/doc/content
    - ${MOOSE_DIR}/modules/heat_transfer/doc/content
    - ${MOOSE_DIR}/modules/rdg/doc/content
    - ${MOOSE_DIR}/modules/ray_tracing/doc/content
    - ${MOOSE_DIR}/modules/stochastic_tools/doc/content
    - ${MOOSE_DIR}/modules/solid_properties/doc/content
    - ${MOOSE_DIR}/modules/misc/doc/content
    - ${MOOSE_DIR}/modules/phase_field/doc/content
    - ${MOOSE_DIR}/modules/solid_mechanics/doc/content
    - modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - media/*
            - help/development/VSCode.md
            - help/development/analyze_jacobian.md
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_development/performance_benchmarking.md
            - application_usage/command_line_usage.md
            - application_usage/restart_recover.md
            - citing.md
    - python:
        root_dir: ${MOOSE_DIR}/python/doc/content
        content:
            - python/mms.md
            - python/MooseDocs/**
            - python/moosesqa/index.md
            - python/source/moosetree/Node.md
            - python/testers/**
            - python/CSVDiff.md
            - python/TestHarness.md

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: TMAP8
        repo: https://github.com/idaholab/TMAP8
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                Using TMAP8: getting_started/using_tmap8.md
                TMAP8 on HPC: getting_started/hpc.md
                User Notes: getting_started/tmap8_user_notes.md
                Contributing to TMAP8: getting_started/contributing.md
            Documentation:
              TMAP8-only Syntax: syntax/tmap_only.md
              Complete Code Syntax: syntax/index.md
              TMAP8 Tutorial Slides: tutorial/index.md
              Theory: theory.md
              V&V: /verification_and_validation/index.md
              Examples: /examples/index.md
              Publications using TMAP8: publications.md
            Software Quality: /sqa/index.md
            Citing: citing_tmap8.md
            Help:
              TMAP8 Issues Page: https://github.com/idaholab/TMAP8/issues
              TMAP8 Discussion Forum: https://github.com/idaholab/TMAP8/discussions
              MOOSE FAQ page: https://mooseframework.inl.gov/help/faq/index.html
              MOOSE Discussion Forum: https://github.com/idaholab/moose/discussions
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            tmap8: !include ${ROOT_DIR}/doc/sqa_tmap8.yml
            heat_transfer: !include ${MOOSE_DIR}/modules/heat_transfer/doc/sqa_heat_transfer.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            navier_stokes: !include ${MOOSE_DIR}/modules/navier_stokes/doc/sqa_navier_stokes.yml
            thermal_hydraulics: !include ${MOOSE_DIR}/modules/thermal_hydraulics/doc/sqa_thermal_hydraulics.yml
            fluid_properties: !include ${MOOSE_DIR}/modules/fluid_properties/doc/sqa_fluid_properties.yml
            rdg: !include ${MOOSE_DIR}/modules/rdg/doc/sqa_rdg.yml
            scalar_transport: !include ${MOOSE_DIR}/modules/scalar_transport/doc/sqa_scalar_transport.yml
            stochastic_tools: !include ${MOOSE_DIR}/modules/stochastic_tools/doc/sqa_stochastic_tools.yml
            solid_properties: !include ${MOOSE_DIR}/modules/solid_properties/doc/sqa_solid_properties.yml
            misc: !include ${MOOSE_DIR}/modules/misc/doc/sqa_misc.yml
            phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/sqa_phase_field.yml
            solid_mechanics: !include ${MOOSE_DIR}/modules/solid_mechanics/doc/sqa_solid_mechanics.yml
        repos:
            default: https://github.com/idaholab/TMAP8
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
    MooseDocs.extensions.template:
        active: true
    MooseDocs.extensions.bibtex:
        duplicates:
            - hales15homogenization
            - kim_phase-field_1999
            - incropera2002
    MooseDocs.extensions.civet:
        test_results_cache: '/tmp/civet/jobs'
        branch: main
        remotes:
            TMAP8:
                url: https://civet.inl.gov
                repo: idaholab/TMAP8
